### ISSUE TITLE
Incorrect conversion of field 'timestamp' of 'version' property

### ISSUE THREAD

**Issue by jochenhebbrecht** [simplexspatial/osm4scala#100]
Hi,

We think we spotted a potential bug in the `OsmPbfRowIterator`. While populating the field `timestamp` of the `version` object, we see a conversion from a Java `Instant` object to a Spark `TimestampType` object (see reference: https://github.com/simplexspatial/osm4scala/blob/master/spark/src/main/scala/com/acervera/osm4scala/spark/OsmPbfRowIterator.scala#L83)
```
case FIELD_INFO_TIMESTAMP => info.timestamp.map(inst => inst.toEpochMilli).getOrElse(null)
```

The field is a time instant in **millis** precision. When we look at the documentation of the `TimestampType` class of Spark (https://spark.apache.org/docs/latest/api/java/org/apache/spark/sql/types/TimestampType.html), the timestamp type actually represents a time instant in micro**second** precision.

Is it possible we mismatch with a factor of 1.000?

Kind regards,
Jochen Hebbrecht

**Comment by angelcervera** [comment]
I double-checked the osm pbf schema to be sure about the type used for timestamps. Looks like in the osm file, timestamps are stored, **in the best case**, with milliseconds precision, so even if Spark is able to store timestamps with microsecond precision, the content will not change (source precision is in milliseconds or seconds).

In fact, the osm timestamp is 32bits (int32 in protobuffer) when the Spark one is 64bits (Long in Scala).

I think that it is not a bug, but maybe I'm missing something.

**Comment by angelcervera** [comment]
@jochenhebbrecht I get your point now. It is expecting microseconds instead of milliseconds. It is a really small difference, but certainly, it is a bug.

**Comment by jochenhebbrecht** [comment]
@angelcervera yes, that was the statement that I wanted to make. Apologies if my original message wasn't clear enough :-)

**Comment by angelcervera** [comment]
@jochenhebbrecht Your original message was clear, don't worry. :)

Here is the PR: https://github.com/simplexspatial/osm4scala/pull/101
Feel free to comment.

**Comment by jochenhebbrecht** [comment]
@angelcervera apologies for late reply. I had a day off today and didn't manage to review the PR yet. 
I just did, and it indeed solves our problem. Thanks, once again, for your great support!
