### ISSUE TITLE
Nodes cannot be read if visible flag is set explicitly to true

### ISSUE THREAD

**Issue by thibauldcroonenborghs-tomtom** [simplexspatial/osm4scala#104]
in [`DenseNodesIterator.scala`](https://github.com/simplexspatial/osm4scala/blob/master/core/src/main/scala/com/acervera/osm4scala/DenseNodesIterator.scala#L58):

```scala
  if (osmosisDenseNode.denseinfo.isDefined && osmosisDenseNode.denseinfo.get.visible.nonEmpty) {
    throw new Exception("Only visible nodes are implemented.")
  }
```

We have encountered a use case where a PBF output by Osmosis has implicitly set the visible flag of nodes to true. Although these nodes are still visible, the exception is thrown because the sequence containing the `visible` flags is not empty.

I would like to suggest a small change where a visible flag set to true is accepted as a correct input.

FYI, I already have some code (+tests) ready on a local branch if you don't mind me contributing and making a PR.

Kind regards,
Thibauld

**Comment by angelcervera** [comment]
Hi @thibauldcroonenborghs-tomtom
Thanks for your time. Of course, feel free to create the PR.

**Comment by angelcervera** [comment]
@thibauldcroonenborghs-tomtom I created a new v1.0.11 It will be available in the maven repo in a few hours. Thanks again.

https://github.com/simplexspatial/osm4scala/releases

**Comment by thibauldcroonenborghs-tomtom** [comment]
Thank YOU @angelcervera for creating and maintaining this repository! and letting us contribute 😉
