### ISSUE TITLE
String encoding

### ISSUE THREAD

**Issue by ericsun95** [simplexspatial/osm4scala#53]
From the code here:
```
private def calculateTags(tags: Map[String, String]): MapData = ArrayBasedMapData(
      tags,
      k => UTF8String.fromString(k.toString),
      v => UTF8String.fromString(v.toString)
    )
```
Why we specify UTF8String, could we make this generic? Some cases the tag string may not use UTF8 which may rise some problems.

**Comment by angelcervera** [comment]
Really good point. It is necessary to research a little bit about this.
My understanding is that OSM is using UTF-8, but I can not find any reference in the documentation.

So few things to do:
- [ ] Confirm that strings are not always UTF-8. We need something official.
- [ ] In case it is not always UTF-8:
   - [ ] How to know the encoding to use?
   - [ ] How to use other encoding in Spark?

I was searching in the documentation, and I did not find anything.
Maybe, osmosis libraries are a good point as reference.

**Comment by angelcervera** [comment]
osmosis is always managing it as UTF-8:
https://github.com/openstreetmap/osmosis/blob/4b1af52a5d9a5eca76e0550b464ea4ce11260e71/osmosis-osm-binary/src/main/java/org/openstreetmap/osmosis/osmbinary/BinaryParser.java#L109

**Comment by angelcervera** [comment]
Ian points to this the reference implementation, that is using always UTF8: https://github.com/openstreetmap/OSM-binary/blob/4e32fa236e919be5bb8dbb323437f026f24e5853/src.java/crosby/binary/StringTable.java#L135

**Comment by angelcervera** [comment]
More information about this: https://help.openstreetmap.org/questions/24589/why-is-the-pbf-stringtable-defined-to-use-byte

**Comment by angelcervera** [comment]
No official documentation about this, but the reference implemenation is using always "UTF-8".
