### ISSUE TITLE
sonarcloud.io integration

### ISSUE THREAD

**Issue by angelcervera** [simplexspatial/osm4scala#60]
Documentation:
- https://docs.travis-ci.com/user/sonarcloud/
- https://sonar-scala.com/docs/setup/sbt-sonar

To use the `sbt-sonar` plugin with sonar-cloud, it is necessary to set the property `sonarExpectSonarQubeCommunityPlugin` to `false`

**Comment by ericsun95** [comment]
Not so familiar with it but it seems really cool.
