### ISSUE TITLE
Support BBox extraction

### ISSUE THREAD

**Issue by ericsun95** [simplexspatial/osm4scala#64]
Similar to the osmosis pbf reader, we should also be able to get the bbox info for extracted entities if it has. Reference: https://github.com/openstreetmap/osmosis/blob/2219470cef1f73f5d1319c57149c84b398e767ce/osmosis-pbf2/src/main/java/org/openstreetmap/osmosis/pbf2/v0_6/impl/PbfBlobDecoder.java#L131-L143

**Comment by angelcervera** [comment]
It sounds interesting, but the scope of the projects is reading pbf files.

osmosis:
Osmosis is a command line Java application for processing Open Street Map (http://www.openstreetmap.org) data.

osm4scala:
Scala library and Spark Connector focus on parsing PBF2 OpenStreetMap files as iterators.

Maybe better to create another project like osmosis bases in osm4scala
