### ISSUE TITLE
Replace all Map for tags to Array/List

### ISSUE THREAD

**Issue by ericsun95** [simplexspatial/osm4scala#72]
Using map here is incorrect. We should use list or array. It could be same key two values in real life pbf and we should keep the data reader not changing anything.

**Comment by angelcervera** [comment]
Are you sure of that? Do you have any example or reference to be sure?
The pbf format stores series of keys,values pointing to the stringTable. Do you mean that there is more than one reference in the same Node/Way/Relation to the same key?
I think that the pbf editor is not support this behaivor.

In that case, this is a bug and it is necessary to change the format to `Map[String, Seq[String]]` (no array or list)

**Comment by angelcervera** [comment]
Confirmed:
From the [OSM documentation](https://wiki.openstreetmap.org/wiki/Multiple_values): 
> As OSM doesn't natively support multiple values for keys (yet), mappers have come up with various MV tagging schemes, each with their pros and cons.

So osm only support one value per key. It will be support in the next 0.7 version.

I'm going to keep it open for the next v2, but definitely is not a bug.

**Comment by angelcervera** [comment]
I'm going to create a tag for osm-0.7 so we can track these things and open it again.

**Comment by ericsun95** [comment]
Iam sure about that. I met a lot of such case. PBF allows it. Please have a look on how other reader like osm2orc，osm parquetizer or osmosis pbf2 read. Array is better than map.

**Comment by ericsun95** [comment]
Don't innovate, just array is enough. Map has more memory footprint too.

**Comment by ericsun95** [comment]
I think changing this ticket back to what it is is better

**Comment by ericsun95** [comment]
For example: https://github.com/openstreetmap/osmosis/blob/master/osmosis-pbf2/src/main/java/org/openstreetmap/osmosis/pbf2/v0_6/impl/PbfBlobDecoder.java#L207-L221

**Comment by angelcervera** [comment]
Looks like you are offended because I change the title. Sorry for that, rolling back.

**Comment by angelcervera** [comment]
If you say that there are cases, even when in the documentation say that it is not supportes, I will beliave your. But understand that I need to check it to be 100% sure.

In the case of suppor of different values per key, I think that tags represent a map of key->value.
It is easy to use and I did not see any problem with the performance.

There are people extracting data from tags (in fact, it is the main use) and Map is the right structure to access by key.

Anyway, let me search cases in the planet to be sure that this is a case. If you want to do it, I will appreciate it.
