### ISSUE TITLE
Move away from Bintray

### ISSUE THREAD

**Issue by angelcervera** [simplexspatial/osm4scala#76]
Currently, Bintray is used for jar publications.
[Bintray will go off next 1st May](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) so I need to migrate the library to another provider.

Options with OSS support or free layer:
- JFrog (the company behind Bintray) offers a [free option](https://jfrog.com/pricing/#sass)
- https://packagecloud.io/pricing
- https://cloudsmith.com/product/pricing/ and https://help.cloudsmith.io/docs/open-source-hosting-policy
- https://github.com/features/packages
- https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/
- 👎🏽 https://docs.aws.amazon.com/codeartifact/latest/ug/welcome.html Needs AWS cli and environment token that expires in 12 hours.
- 👎🏽 https://cloud.google.com/artifact-registry The only repository type that is not in Alpha is the Docker one.
- https://ossindex.sonatype.org directly: https://www.scala-sbt.org/1.x/docs/Using-Sonatype.html
- https://www.cloudrepo.io/ ??
- https://www.ibm.com/ie-en/cloud/urbancode ??

Other useful Links:
- https://central.sonatype.org/pages/ossrh-guide.html
- https://maven.apache.org/repository/guide-central-repository-upload.html
- #5
- https://www.acervera.com/blog/2020/04/sbt-crossversion-release-bintray/

Tools helping to publish: https://github.com/olafurpg/sbt-ci-release

Links related to the current project status:
- https://issues.sonatype.org/browse/OSSRH-57177
- https://oss.sonatype.org

Publishing directly to Sonatype:
- https://github.com/xerial/sbt-sonatype
- https://leonard.io/blog/2017/01/an-in-depth-guide-to-deploying-to-maven-central/
- https://medium.com/rahasak/publish-scala-library-project-to-maven-central-with-sonatype-d7edaa67d275
- https://www.scala-sbt.org/1.x/docs/Using-Sonatype.html

Don't forget to update all bintray badges from the documentation!!!

**Comment by lskillen** [comment]
Hello! I work at Cloudsmith, and we'd be delighted to help out. Let us know if you have any questions. :-)

**Comment by angelcervera** [comment]
Hi @lskillen I used Bintray to store snapshots, releases candidates and the really helpful option to synchronize releases with maven central account.
The last feature (sync with maven central) is the one that I can not find in any other provider.
Do you have it?

**Comment by lskillen** [comment]
> Do you have it?

Not yet, unfortunately, and you're right, it was Bintray-specific. I'm not certain it's something that we'll 100% do, but we've certainly discussed it. From what I recall, some of the issues for publishing to Maven Central were related to the processes of requiring things like signatures and perhaps just a "canonical form" for the packages. We're primarily for the distribution itself rather than passthrough, but we can certainly act as a staging area for assets by helping with things such as automatic signing.
