### ISSUE TITLE
More examples and documentation

### ISSUE THREAD

**Issue by angelcervera** [simplexspatial/osm4scala#9]
It includes:
- [x] Website with tutorial (https://docusaurus.io/)
- [x] Move the minimum coverage to 90% instead of the current 80%
- [x] Integration test for Spark connectors: #61

**Comment by ericsun95** [comment]
I think we need add more unit tests and some end-to-end integration test to make sure no weird things happen in this conversion process.

**Comment by angelcervera** [comment]
The test coverage in the last released was 94% and in the master now is 89%. Still a good coverage, but better to have more testing to use it as documentation and examples as well.
The end to end example is a great idea.

What do you think about writing more articles and posts with use cases?

**Comment by angelcervera** [comment]
BTW, there is a folder in the repo with a 8 different examples.
