### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by Kazerujoy** [simplexspatial/osm4scala#90]
hello, i try to read osm files by osm4scala in spark with maven, i add the dependence in maven and do the spark.read.format('osm.pbf').load(). The exception say there Failed to find data source:osm.pbf.  how can i deal with this problem?

**Comment by angelcervera** [comment]
https://github.com/simplexspatial/osm4scala/discussions/77#discussioncomment-923504
